export const sectionAFormStates = {
  hospitalName: '',
  address: '',
  landmark: '',
  city: '',
  pinCode: 0,
  website: '',
  googleLink: '',
  state: '',
  phoneNo: 0,
  email: '',
}

export const sectionBFormStates = {
  insurancePersonName: '',
  insurancePersonEmail: '',
  insurancePersonPhoneNo: 0,
  accountsPersonName: '',
  accountsPersonEmail: '',
  accountsPersonPhoneNo: 0,
  marketingHeadName: '',
  marketingHeadEmail: '',
  marketingHeadPhoneNo: 0,
  medicalDirectorName: '',
  medicalDirectorEmail: '',
  medicalDirectorPhoneNo: 0,
  kenkoSPOCName: '',
  kenkoSPOCEmail: '',
  kenkoSPOCPhoneNo: 0,
  adminHeadName: '',
  adminHeadEmail: '',
  adminHeadPhoneNo: 0,
}

export const sectionCFormStates = {
  bankName: '',
  bankBranch: '',
  accountType: '',
  accountNo: 0,
  ifscCode: '',
  micrCode: '',
  cancelChequeNo: 0,
  upiId: '',
}

export const sectionDFormStates = {
  payeeHospitalName: '',
  payeeName: '',
  panNo: 0,
  panHolderName: '',
}

export const sectionEFormStates = {
  noOfBeds: 0,
  hospitalRegistrationNo: '',
  registeringAuthorityName: '',
  facilityType: '',
  rohiniId: '',
  general: '',
  maternityRoom: '',
  specialized: '',
  intensiveCareUnit: '',
  intensiveCriticalCareUnit: '',
  medicalIcu: '',
  pediatricIcu: '',
  surgicalIcu: '',
  parkingFacility: '',
  accessibility: false,
  codingAndBilling: false,
  waitingRoom: false,
  canteen: false,
  computerizedBilling: false,
  patientFoodIncludedInAccommodation: false,
  std: false,
  telephoneAccessToWards: false,
}

export const sectionFFormStates = {
  acBedName: '',
  acBedCount: 0,
  acSingleBedName: '',
  acSingleBedCount: 0,
  nonAcSingleBedName: '',
  nonAcSIngleBedCount: 0,
  acTwinSharingBedName: '',
  acTwinSharingBedCount: 0,
  nonAcTwinSharingBedName: '',
  nonAcTwinSharingBedCount: 0,
  multiSharingBedName: '',
  multiSharingBedCount: 0,
  generalWardBedName: '',
  generalWardBedCount: 0,
  icuBedName: '',
  icuBedCount: 0,
  iccuBedName: '',
  iccuBedCount: 0,
  micuBedName: '',
  micuBedCount: 0,
  sicuBedName: '',
  sicuBedCount: 0,
  picuBedName: '',
  picuBedCount: 0,
}

export const sectionGFormStates = {
  noOfDoctors: 0,
  noOfConsultants: 0,
  noOfSurgeons: 0,
  noOfQualifiedNurses: 0,
  noOfIcuNurses: 0,
  noOfIcuDoctors: 0,
}

export const sectionHFormStates = {
  ownership: '',
  fieldOfMedicine: '',
  accredition: '',
}

export const sectionIFormStates = {
  generalMedicineOpd: '',
  generalMedicineIpd: '',
  generalMedicineSI: '',
  generalSurgeryOpd: '',
  generalSurgeryIpd: '',
  generalSurgerySI: '',
  pediatricsOpd: '',
  pediatricsIpd: '',
  pediatricsSI: '',
  orthopedicOpd: '',
  orthopedicIpd: '',
  orthopedicSI: '',
  ophthalmologyOpd: '',
  ophthalmologyIpd: '',
  ophthalmologySI: '',
  earNoseAndThroatOpd: '',
  earNoseAndThroatIpd: '',
  earNoseAndThroatSI: '',
  gynecologyAndObstetricsOpd: '',
  gynecologyAndObstetricsIpd: '',
  gynecologyAndObstetricsSI: '',
  cardiacOpd: '',
  cardiacIpd: '',
  cardiacSI: '',
  neurologyOpd: '',
  neurologyIpd: '',
  neurologySI: '',
  urologyOpd: '',
  urologyIpd: '',
  urologySI: '',
  oncologyOpd: '',
  oncologyIpd: '',
  oncologySI: '',
  nephrologyOpd: '',
  nephrologyIpd: '',
  nephrologySI: '',
  plasticSurgeryOpd: '',
  plasticSurgeryIpd: '',
  plasticSurgerySI: '',
  burnsOpd: '',
  burnsIpd: '',
  burnsSI: '',
  hematologyOpd: '',
  hematologyIpd: '',
  hematologySI: '',
  organTransplantOpd: '',
  organTransplantIpd: '',
  organTransplantSI: '',
  radiationTherapyOpd: '',
  radiationTherapyIpd: '',
  radiationTherapySI: '',
  autoClaving: '',
  ionizingRadiations: '',
  fumigation: '',
  others: '',
  pharmacy: '',
  rmo: '',
  pathology: '',
  nursing: '',
  fullTimeDoctors: '',
  houseKeeping: '',
  emergency: '',
  laundry: '',
  security: '',
  ambulance: '',
  cathLab: '',
  generalAmbulance: '',
  cardiacAmbulance: '',
  neonatalAmbulance: '',
  ventilatorAmbulance: '',
  doctorAccompanyingAmbulance: '',
  bloodBank: '',
  mortuary: '',
  dialysis: '',
  otTable: '',
  laminarAirFlow: '',
  cardiacDefibrillator: '',
  electrocautery: '',
  suction: '',
  cArm: '',
  cardiacMonitor: '',
}
export const sectionJFormStates = {
  doctorBedRatio: '',
  averageAdmissionTime: '',
  averageDischargeTime: '',
  nurseBedRatio: '',
  doctorBedRatioIcu: '',
}

export const sectionKFormStates = {
  hospitalRegistrationCertificate: '',
  doctorResignationCertificate: '',
  panCardCopy: '',
  discountLetter: '',
  cancelledCheque: '',
  listOfDoctors: '',
  tariffList: '',
  agreement: '',
  listOfConsultantsOpd: '',
  hospitalPhotographs: '',
  nabh: '',
  listOfInsuranceCompanies: '',
}
