export const sectionIClinicalServices = [
  {
    title: 'General Medicine:',
    fieldName: 'GENERAL_MEDICINE',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        service: 'GENERAL_MEDICINE',
        isViewOnly: false,
        isHide: false,
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',

        isViewOnly: false,
        isHide: false,
        service: 'GENERAL_MEDICINE',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'GENERAL_MEDICINE',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'General Surgery:',
    fieldName: 'GENERAL_SURGERY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'GENERAL_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'GENERAL_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'GENERAL_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Pediatrics:',
    fieldName: 'PEDIATRICS',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'PEDIATRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'PEDIATRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'PEDIATRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Orthopedic:',
    fieldName: 'ORTHOPEDIC',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ORTHOPEDIC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ORTHOPEDIC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'ORTHOPEDIC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Ophthalmology:',
    fieldName: 'OPHTHALMOLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'OPHTHALMOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'OPHTHALMOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'OPHTHALMOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Ear, Nose & Throat:',
    fieldName: 'ENT',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ENT',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ENT',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'ENT',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Gynecology & Obstetrics:',
    fieldName: 'GYNECOLOGY_AND_OBSTETRICS',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'GYNECOLOGY_AND_OBSTETRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'GYNECOLOGY_AND_OBSTETRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'GYNECOLOGY_AND_OBSTETRICS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Cardiac:',
    fieldName: 'CARDIAC',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'CARDIAC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'CARDIAC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'CARDIAC',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Neurology:',
    fieldName: 'NEUROLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'NEUROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'NEUROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'NEUROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Urology:',
    fieldName: 'UROLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'UROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'UROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'UROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Oncology:',
    fieldName: 'ONCOLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ONCOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ONCOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'ONCOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Nephrology:',
    fieldName: 'NEPHROLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'NEPHROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'NEPHROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'NEPHROLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Plastic/Reconstruction Surgery:',
    fieldName: 'PLASTIC_OR_RECONSTRUCTION_SURGERY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'PLASTIC_OR_RECONSTRUCTION_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'PLASTIC_OR_RECONSTRUCTION_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'PLASTIC_OR_RECONSTRUCTION_SURGERY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Burns:',
    fieldName: 'BURNS',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'BURNS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'BURNS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'BURNS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Hematology:',
    fieldName: 'HEMATOLOGY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'HEMATOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'HEMATOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'HEMATOLOGY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Organ Transplant:',
    fieldName: 'ORGAN_TRANSPLANTS',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ORGAN_TRANSPLANTS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'ORGAN_TRANSPLANTS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'ORGAN_TRANSPLANTS',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
  {
    title: 'Radiation Therapy:',
    fieldName: 'RADIATION_THERAPY',
    forms: [
      {
        name: 'opd',
        type: 'select',
        label: 'OPD:',
        isViewOnly: false,
        isHide: false,
        service: 'RADIATION_THERAPY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'ipd',
        type: 'select',
        label: 'IPD:',
        isViewOnly: false,
        isHide: false,
        service: 'RADIATION_THERAPY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
      {
        name: 'surgicalInterventions',
        type: 'select',
        label: 'Surgical Interventions:',
        isViewOnly: false,
        isHide: false,
        service: 'RADIATION_THERAPY',
        options: [
          { key: 'Yes', value: 'YES' },
          { key: 'No', value: 'NO' },
        ],
      },
    ],
  },
]

export const sectionISterilizationPractice = [
  {
    name: 'availability',
    type: 'select',
    label: 'Autoclaving:',
    isViewOnly: false,
    isHide: false,
    service: 'AUTOCLAVING',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Ionizing/Non-Ionizing (UV) Radiations:',
    isViewOnly: false,
    isHide: false,
    service: 'LONIZING_OR_NON_LONIZING_UV_RADIATIONS',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Fumigation:',
    isViewOnly: false,
    isHide: false,
    service: 'FUMIGATION',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Others (please specify):',
    isViewOnly: false,
    isHide: false,
    service: 'OTHERS_PLEASE_SPECIFY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
]

export const sectionIInHouseServices = [
  {
    name: 'availability',
    type: 'select',
    label: 'Pharmacy:',
    isViewOnly: false,
    isHide: false,
    service: 'PHARMACY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: "RMO's:",
    isViewOnly: false,
    isHide: false,
    service: 'RMOS',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Pathology:',
    isViewOnly: false,
    isHide: false,
    service: 'PATHOLOGY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Nursing:',
    isViewOnly: false,
    isHide: false,
    service: 'NURSING',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Full time doctors:',
    isViewOnly: false,
    isHide: false,
    service: 'FULL_TIME_DOCTORS',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'House Keeping:',
    isViewOnly: false,
    isHide: false,
    service: 'HOUSEKEEPING',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Emergency/Maintenance:',
    isViewOnly: false,
    isHide: false,
    service: 'EMERGENCY_OR_MAINTENANCE',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Laundry:',
    isViewOnly: false,
    isHide: false,
    service: 'LAUNDRY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Security:',
    isViewOnly: false,
    isHide: false,
    service: 'SECURITY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Ambulance:',
    isViewOnly: false,
    isHide: false,
    service: 'AMBULANCE',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Cath lab:',
    service: 'CATH_LAB',
    isViewOnly: false,
    isHide: false,
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: '(a) General:',
    isViewOnly: false,
    isHide: false,
    service: 'GENERAL_AMB',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Blood Bank:',
    isViewOnly: false,
    isHide: false,
    service: 'BLOOD_BANK',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: '(b) Cardiac:',
    isViewOnly: false,
    isHide: false,
    service: 'CARDIAC_AMB',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Mortuary:',
    isViewOnly: false,
    isHide: false,
    service: 'MORTUARY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: '(c) Neonatal:',
    isViewOnly: false,
    isHide: false,
    service: 'NEONATAL_AMB',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Dialysis:',
    isViewOnly: false,
    isHide: false,
    service: 'DIALYSIS',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: '(d) Ventilator Support:',
    isViewOnly: false,
    isHide: false,
    service: 'VENTILATOR_SUPPORT_AMB',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: '(e) Doctor Accompanying:',
    isViewOnly: false,
    isHide: false,
    service: 'DOCTOR_ACCOMPANYING_AMB',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
]

export const sectionIOtDescription = [
  {
    name: 'availability',
    type: 'select',
    label: 'OT Table (Hydrulic/Manual):',
    isViewOnly: false,
    isHide: false,
    service: 'OT_TABLE_HYDRAULIC_OR_MANUAL',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Laminar Air flow:',
    isViewOnly: false,
    isHide: false,
    service: 'LAMINAR_AIR_FLOW',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Cardiac Defibrillator:',
    isViewOnly: false,
    isHide: false,
    service: 'CARDIAC_DEFIBRILLATOR',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Electrocautery:',
    isViewOnly: false,
    isHide: false,
    service: 'ELECTROCAUTERY',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Suction:',
    isViewOnly: false,
    isHide: false,
    service: 'SUCTION',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'C-Arm/Boyle’s:',
    isViewOnly: false,
    isHide: false,
    service: 'CARM_OR_BOYLES',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
  {
    name: 'availability',
    type: 'select',
    label: 'Cardiac Monitor',
    isViewOnly: false,
    isHide: false,
    service: 'CARDIAC_MONITOR',
    options: [
      { key: 'Yes', value: 'YES' },
      { key: 'No', value: 'NO' },
    ],
  },
]
